name: authorization_feature
description: Authorization (login) feature module for Stock Pro
version: 0.0.1
publish_to: 'none'

resolution: workspace

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
